spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./nbe2_2_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

