spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: seodo1e1205@gmail.com
    password: nnjd usla bvhe crsd
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      debug : true

  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./nbe2_2_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    com.example.devcoursed: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE